/**
 * Tag glossary mapping dimensions to their available tags
 * Based on: /Users/yasharm/tools-v3/0 – Tagging and organization logic (NO PUBLISH)/Tag glossary.md
 */

export const TAG_GLOSSARY: Record<string, string[]> = {
  resourceType: [
    'academic-articles',
    'book',
    'case-study',
    'method',
    'tool',
    'software-tool',
    'toolkit',
    'template',
    'framework',
    'online-course',
    'canvas',
    'whitepaper',
  ],
  objective: [
    'map',
    'assess',
    'report',
    'align',
  ],
  targetAudience: [
    'entrepreneurs',
    'researchers',
    'students',
    'policy-makers',
    'investors',
    'educators',
    'practitioners',
    'nonprofits',
    'startups',
    'SMEs',
    'corporations',
    'general-public',
  ],
  sustainabilityFocus: [
    'environmental-sustainability',
    'social-sustainability',
    'economic-sustainability',
    'environmental-impact',
    'social-impact',
    'economic-impact',
    'circular-economy',
    'governance',
    'CSR',
    'SDGs',
  ],
  innovationType: [
    'product-innovation',
    'process-innovation',
    'business-model-innovation',
    'social-innovation',
    'technological-innovation',
    'open-innovation',
  ],
  entrepreneurshipStage: [
    'ideation',
    'design',
    'development',
    'implementation',
    'startup',
    'growth',
    'scale-up',
    'maturity',
  ],
  scope: [
    'global',
    'regional',
    'national',
    'local',
    'urban',
    'rural',
  ],
  methodology: [
    'qualitative-research',
    'quantitative-research',
    'mixed-methods',
    'experimental-design',
    'theoretical-frameworks',
  ],
  skillDevelopment: [
    'leadership-and-management',
    'creativity-and-design',
    'financial-literacy',
    'marketing-and-communication',
    'technical-skills',
    'networking-and-collaboration',
    'systems-thinking',
    'holistic-thinking',
    'environmental-awareness',
    'innovative-thinking',
    'adaptability-and-resilience',
    'business-and-financial-skills',
    'collaboration-and-networking',
    'data-analysis-and-metrics',
    'communication-and-storytelling',
    'regulatory-and-legal-understanding',
  ],
  sourceCredibility: [
    'peer-reviewed-publications',
    'government-sources',
    'reputable-industry-sources',
    'academic-institutions',
    'recognized-experts',
    'practice',
    'research',
  ],
  prerequisites: [
    'none',
    'beginner-level',
    'intermediate-level',
    'advanced-level',
    'expert-level',
    'specific-educational-background',
    'required-equipment-or-aids',
    'facilitators',
  ],
  collaborationLevel: [
    'individual',
    'team',
    'community',
    'cross-sector-partnerships',
    'public-private-partnership',
    'community-engagement',
  ],
};
